### PR TITLE
mega vg build and dependency cleanup

### PR DESCRIPTION
**Pull request by ekg**
To discuss.

### CODE REVIEW

**Comment by ekg** [comment]
In trying to build your fork, when I pulled and got:

```
Unable to checkout 'e5fb7f3b15ec49edc3fc6293797b44cc7ce420cc' in submodule path 'deps/lru_cache'
```

Is it possible that you have this locally? Or did github break (again)?

**Comment by ekg** [comment]
Travis has the same issue:

https://travis-ci.org/ekg/vg/builds/90324849#L210-L227

```
Unable to checkout 'e5fb7f3b15ec49edc3fc6293797b44cc7ce420cc' in submodule path 'deps/lru_cache'
The command "eval git submodule update" failed. Retrying, 2 of 3.
fatal: reference is not a tree: e5fb7f3b15ec49edc3fc6293797b44cc7ce420cc
Unable to checkout 'e5fb7f3b15ec49edc3fc6293797b44cc7ce420cc' in submodule path 'deps/lru_cache'
The command "eval git submodule update" failed. Retrying, 3 of 3.
fatal: reference is not a tree: e5fb7f3b15ec49edc3fc6293797b44cc7ce420cc
Unable to checkout 'e5fb7f3b15ec49edc3fc6293797b44cc7ce420cc' in submodule path 'deps/lru_cache'
The command "eval git submodule update" failed 3 times.
The command "git submodule update" failed and exited with 1 during .
```

**Comment by edawson** [comment]
Yep, I had added a gitignore on my local branch and that broke it. I've moved to my fork for the submodule and will submit a PR for lru_cache.

Oops.

**Comment by ekg** [comment]
Now we get https://travis-ci.org/ekg/vg/builds/90326162#L2724-L2732

```
ar: creating librocksdb.a
make[1]: Leaving directory `/home/travis/build/ekg/vg/deps/rocksdb'
protoc src/vg.proto --proto_path=src --cpp_out=cpp
make: protoc: Command not found
make: *** [cpp/vg.pb.h] Error 127
The command "make && make test" exited with 2.
Done. Your build exited with 1.
```

**Comment by edawson** [comment]
Yep, xg wouldn't take my stream update for some reason. I'm working on it.

**Comment by ekg** [comment]
:hammer: :wrench:

**Comment by edawson** [comment]
Update: now goes to 11.

screen shot 2015-11-12 at 12 30 34 am

**Comment by ekg** [comment]
Looking good. Merging.

**Pull request merged**
