### PR TITLE
update README about open issues

### PR DESCRIPTION
**Pull request by ryan-williams**

### CODE REVIEW

**Comment by ekg** [comment]
I like the idea of listing features here rather than open issues. Maybe this whole section should move to the wiki? It is motivating to see both what has been done and what remains.

**Comment by ryan-williams** [comment]
yea, I'm open to what you prefer; agreed that an enumeration of some things that are supported is useful, and the checked items here are a reasonable proxy for that

**Comment by ryan-williams** [comment]
which wiki are you referring to btw? does one exist, or are you suggesting initializing the github-repo-wiki for this project?

**Comment by ekg** [comment]
What about this: let's keep the completed todo items as features, and for the new ones add links to the issues. Thoughts?

A few people have mentioned that the todo list is actually helpful, so I'm reluctant to give it up.

**Comment by ryan-williams** [comment]
Either way works for me. I've updated this PR to put the "to-do" items in their own list and link to associated issues. There are other issues that are/were not in that list (anything before #10), I can add them if you like. Does this also suggest that people should add new issues filed to the README.md?

I can also leave it alone / close this, whatever you like.

**Pull request closed without merging**
